<?php

function getSettings($conn) {
    $result = $conn->query("SELECT * FROM settings WHERE id = 1");
    return $result->fetch_assoc();
}

function getSeoSettings($conn) {
    $result = $conn->query("SELECT * FROM seo_settings WHERE id = 1");
    return $result->fetch_assoc();
}

function getAdsByLocation($conn, $location) {
    $now = date('Y-m-d');
    $stmt = $conn->prepare("SELECT * FROM ads WHERE location = ? AND is_active = 1 AND (expiry_date IS NULL OR expiry_date >= ?)");
    $stmt->bind_param("ss", $location, $now);
    $stmt->execute();
    return $stmt->get_result();
}

function getAd($conn, $slot_name) {
    // Mapping old slot names to new locations for backward compatibility
    $mapping = [
        'header_top' => 'header_text_link',
        'mid_content' => 'body_text_link',
        'result_footer' => 'footer_link'
    ];

    $location = $mapping[$slot_name] ?? $slot_name;

    $ads = getAdsByLocation($conn, $location);
    if ($ad = $ads->fetch_assoc()) {
        if ($ad['position'] == 'image') {
            return '<a href="'.htmlspecialchars($ad['anchor_link']).'" target="_blank"><img src="'.htmlspecialchars($ad['image_url']).'" alt="Ad"></a>';
        } elseif (!empty($ad['anchor_link']) && !empty($ad['anchor_text'])) {
            return '<a href="'.htmlspecialchars($ad['anchor_link']).'" target="_blank" class="text-emerald-600 font-bold hover:underline">'.htmlspecialchars($ad['anchor_text']).'</a>';
        }
        return $ad['ad_code'];
    }
    return '';
}

function getCurrentSeasonRange() {
    $year = (int)date('Y');
    $month = (int)date('n');
    $seasonStartYear = $month >= 7 ? $year : $year - 1;
    return $seasonStartYear . '/' . ($seasonStartYear + 1);
}

function sanitize($input) {
    return htmlspecialchars(strip_tags(trim($input)));
}

function ensureDatabaseTablesExist($conn) {
    static $alreadyRun = false;
    if ($alreadyRun) return;
    $alreadyRun = true;

    $charset = "ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci";

    // 1. Create Core Tables First
    $conn->query("CREATE TABLE IF NOT EXISTS `settings` (`id` INT PRIMARY KEY DEFAULT 1, `site_name` VARCHAR(255) DEFAULT 'SurePredictor', `site_description` TEXT, `primary_color` VARCHAR(20) DEFAULT '#059669', `dark_mode` TINYINT(1) DEFAULT 0) $charset");
    $conn->query("INSERT IGNORE INTO `settings` (`id`, `site_name`, `site_description`) VALUES (1, 'SurePredictor', 'Global football insights powered by advanced AI.')");

    $conn->query("CREATE TABLE IF NOT EXISTS `seo_settings` (`id` INT PRIMARY KEY DEFAULT 1, `meta_title` VARCHAR(255), `meta_description` TEXT, `og_image` VARCHAR(255)) $charset");
    $conn->query("INSERT IGNORE INTO `seo_settings` (`id`, `meta_title`, `meta_description`) VALUES (1, 'SurePredictor - AI Football Predictions', 'Professional football insights and match forecasts generated by advanced AI.')");

    $conn->query("CREATE TABLE IF NOT EXISTS `admins` (`id` INT AUTO_INCREMENT PRIMARY KEY, `username` VARCHAR(50) UNIQUE NOT NULL, `password_hash` VARCHAR(255) NOT NULL, `last_login` DATETIME) $charset");

    $conn->query("CREATE TABLE IF NOT EXISTS `visitors` (`id` INT AUTO_INCREMENT PRIMARY KEY, `user_id` VARCHAR(50) UNIQUE NOT NULL, `email` VARCHAR(255), `username` VARCHAR(100), `password_hash` VARCHAR(255), `full_name` VARCHAR(255), `phone` VARCHAR(50), `credits` DECIMAL(10,2) DEFAULT 0.00, `total_predictions` INT DEFAULT 0, `status` ENUM('active', 'suspended') DEFAULT 'active', `fingerprint` VARCHAR(255), `ip_address` VARCHAR(45), `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP) $charset");
    $conn->query("CREATE TABLE IF NOT EXISTS `credit_packages` (`id` INT AUTO_INCREMENT PRIMARY KEY, `name` VARCHAR(255) NOT NULL, `price_usd` DECIMAL(10,2) NOT NULL, `credits` DECIMAL(10,2) NOT NULL, `description` TEXT, `status` TINYINT(1) DEFAULT 1) $charset");
    $conn->query("CREATE TABLE IF NOT EXISTS `payment_notifications` (`id` INT AUTO_INCREMENT PRIMARY KEY, `visitor_id` INT, `package_id` INT, `amount` DECIMAL(10,2), `currency` VARCHAR(10), `proof_file` VARCHAR(255), `status` ENUM('pending', 'approved', 'cancelled') DEFAULT 'pending', `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP) $charset");
    $conn->query("CREATE TABLE IF NOT EXISTS `news_categories` (`id` INT AUTO_INCREMENT PRIMARY KEY, `name` VARCHAR(100) NOT NULL, `slug` VARCHAR(100) UNIQUE NOT NULL, `description` TEXT) $charset");
    $conn->query("INSERT IGNORE INTO `news_categories` (`id`, `name`, `slug`) VALUES (1, 'General', 'general')");

    $conn->query("CREATE TABLE IF NOT EXISTS `news` (`id` INT AUTO_INCREMENT PRIMARY KEY, `title` VARCHAR(255) NOT NULL, `slug` VARCHAR(255) UNIQUE, `content` LONGTEXT, `image_url` VARCHAR(255), `category_id` INT DEFAULT 1, `author_id` INT DEFAULT 1, `source` VARCHAR(100), `views` INT DEFAULT 0, `is_featured` TINYINT(1) DEFAULT 0, `is_trending` TINYINT(1) DEFAULT 0, `meta_description` TEXT, `meta_keywords` VARCHAR(255), `published_at` DATETIME, `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP, `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, UNIQUE KEY `news_title` (`title`)) $charset");
    $conn->query("CREATE TABLE IF NOT EXISTS `daily_usage` (`id` INT AUTO_INCREMENT PRIMARY KEY, `identifier` VARCHAR(255) NOT NULL, `usage_count` INT DEFAULT 0, `last_usage_date` DATE, UNIQUE KEY `daily_usage_idx` (`identifier`, `last_usage_date`)) $charset");
    $conn->query("CREATE TABLE IF NOT EXISTS `sessions` (`id` VARCHAR(128) NOT NULL PRIMARY KEY, `data` MEDIUMTEXT NOT NULL, `last_access` INT(11) NOT NULL) $charset");
    $conn->query("CREATE TABLE IF NOT EXISTS `ads` (`id` INT AUTO_INCREMENT PRIMARY KEY, `slot_name` VARCHAR(50), `ad_code` TEXT, `is_active` BOOLEAN DEFAULT TRUE) $charset");
    $conn->query("CREATE TABLE IF NOT EXISTS `user_history` (`id` INT AUTO_INCREMENT PRIMARY KEY, `user_id` VARCHAR(50), `home_team` VARCHAR(100), `away_team` VARCHAR(100), `result_json` LONGTEXT, `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP) $charset");
    $conn->query("CREATE TABLE IF NOT EXISTS `prediction_cache` (`id` INT AUTO_INCREMENT PRIMARY KEY, `match_hash` VARCHAR(64) UNIQUE, `home_team` VARCHAR(100), `away_team` VARCHAR(100), `result_json` LONGTEXT, `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP) $charset");
    $conn->query("CREATE TABLE IF NOT EXISTS `online_transactions` (`id` INT AUTO_INCREMENT PRIMARY KEY, `visitor_id` INT, `package_id` INT, `transaction_ref` VARCHAR(100) UNIQUE, `amount` DECIMAL(10,2), `currency` VARCHAR(10), `gateway` VARCHAR(50), `status` ENUM('pending', 'success', 'failed') DEFAULT 'pending', `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP) $charset");

    // 2. Handle Schema Updates (Columns)
    $columns = [
        'ai_provider' => "VARCHAR(20) DEFAULT 'gemini'",
        'deepseek_api_key' => "VARCHAR(255)",
        'deepseek_model_prediction' => "VARCHAR(100)",
        'deepseek_model_suggestion' => "VARCHAR(100)",
        'deepseek_base_url' => "VARCHAR(255) DEFAULT 'https://api.deepseek.com/'",
        'site_logo' => "VARCHAR(255)",
        'site_icon' => "VARCHAR(255)",
        'gemini_model_prediction' => "VARCHAR(100)",
        'gemini_model_suggestion' => "VARCHAR(100)",
        'free_limit' => "INT DEFAULT 3",
        'prediction_charge' => "DECIMAL(10,2) DEFAULT 0.03",
        'whatsapp_number' => "VARCHAR(20)",
        'whatsapp_text' => "TEXT",
        'paystack_public_key' => "VARCHAR(255)",
        'paystack_secret_key' => "VARCHAR(255)",
        'flutterwave_public_key' => "VARCHAR(255)",
        'flutterwave_secret_key' => "VARCHAR(255)",
        'primary_currency' => "VARCHAR(10) DEFAULT 'USD'",
        'conversion_rate_ngn' => "DECIMAL(10,2) DEFAULT 1500.00",
        'conversion_rate_kes' => "DECIMAL(10,2) DEFAULT 130.00",
        'bank_details_ngn' => "TEXT",
        'bank_details_kes' => "TEXT",
        'ad_expiry_date' => "DATE",
        'news_enabled' => "TINYINT(1) DEFAULT 1",
        'history_enabled' => "TINYINT(1) DEFAULT 1",
        'beewave_access_key' => "VARCHAR(255)"
    ];

    $visitor_cols = [
        'total_predictions' => "INT DEFAULT 0",
        'password_hash' => "VARCHAR(255)",
        'full_name' => "VARCHAR(255)",
        'username' => "VARCHAR(100)",
        'status' => "ENUM('active', 'suspended') DEFAULT 'active'"
    ];

    foreach ($visitor_cols as $col => $def) {
        $check = $conn->query("SHOW COLUMNS FROM `visitors` LIKE '$col'");
        if ($check && $check->num_rows == 0) {
            $conn->query("ALTER TABLE `visitors` ADD `$col` $def");
        }
    }

    foreach ($columns as $col => $def) {
        $check = $conn->query("SHOW COLUMNS FROM `settings` LIKE '$col'");
        if ($check && $check->num_rows == 0) {
            $conn->query("ALTER TABLE `settings` ADD `$col` $def");
        }
    }

    // Remove unique constraint from ads slot_name if it exists
    $check_unique = $conn->query("SHOW INDEX FROM `ads` WHERE Column_name = 'slot_name' AND Non_unique = 0");
    if ($check_unique && $check_unique->num_rows > 0) {
        $index_name = $check_unique->fetch_assoc()['Key_name'];
        $conn->query("ALTER TABLE `ads` DROP INDEX `$index_name` ");
    }

    $ad_columns = [
        'position' => "VARCHAR(50)",
        'location' => "VARCHAR(50)",
        'anchor_link' => "VARCHAR(255)",
        'anchor_text' => "VARCHAR(255)",
        'price' => "DECIMAL(10,2)",
        'expiry_date' => "DATE",
        'client_contact' => "VARCHAR(255)",
        'image_url' => "VARCHAR(255)"
    ];

    foreach ($ad_columns as $col => $def) {
        $check = $conn->query("SHOW COLUMNS FROM `ads` LIKE '$col'");
        if ($check && $check->num_rows == 0) {
            $conn->query("ALTER TABLE `ads` ADD `$col` $def");
        }
    }

    // Handle News Schema Updates
    $news_cols = [
        'slug' => "VARCHAR(255) UNIQUE",
        'category_id' => "INT DEFAULT 1",
        'author_id' => "INT DEFAULT 1",
        'views' => "INT DEFAULT 0",
        'is_featured' => "TINYINT(1) DEFAULT 0",
        'is_trending' => "TINYINT(1) DEFAULT 0",
        'meta_description' => "TEXT",
        'meta_keywords' => "VARCHAR(255)",
        'published_at' => "DATETIME",
        'updated_at' => "TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"
    ];
    foreach ($news_cols as $col => $def) {
        $check = $conn->query("SHOW COLUMNS FROM `news` LIKE '$col'");
        if ($check && $check->num_rows == 0) {
            $conn->query("ALTER TABLE `news` ADD `$col` $def");
        }
    }

    // Ensure user_id in prediction_cache
    $check_cache = $conn->query("SHOW COLUMNS FROM `prediction_cache` LIKE 'user_id'");
    if ($check_cache && $check_cache->num_rows == 0) {
        $conn->query("ALTER TABLE `prediction_cache` ADD `user_id` VARCHAR(50) AFTER `id` ");
    }
}

?>
